### ISSUE TITLE
Blank powerline while opening a javascript source file

### ISSUE THREAD

**Issue by jilen** [AnthonyDiGirolamo/airline-themes#10]
Also reported here
https://github.com/milkypostman/powerline/issues/98

**Comment by AnthonyDiGirolamo** [comment]
Hey @jilen,
I had some bugs in the shorten-directory function that was causing blank modelines for me when in a TRAMP buffer. I've replaced that function which works for me now in TRAMP buffers. Could you give it a try with the latest code? I tagged it with version 1.2. If it still doesn't work can you provide a file and the directory it lives under so I can try to reproduce the error? Thanks!

**Comment by jilen** [comment]
@AnthonyDiGirolamo  After upgrading to the latest version, it was fixed. Thx very much !
