### ISSUE TITLE
Colored rectangluar

### ISSUE THREAD

**Issue by kczapla** [AnthonyDiGirolamo/airline-themes#16]
Any airline theme I set, changes modeline to colored rectangle. Can u give more details how to setup it correctly?

**Comment by hackel** [comment]
I'm experiencing this as well.  Appears to be similar to #10.  The odd thing is that I initially set everything up by cloning the packages into my ~/.emacs.d manually and it all worked fine.  Then I switched to Melpa and started experiencing this blank line issue.  I don't get any error messages or anything.

If I tate `(load-theme 'airline-dark)` out of my init.rc, powerline loads fine.  If I then manually load a theme, it kind-of displays correctly.  If I then run `airline-themes-set-modeline` it disappears again completely.  Here's my init.rc:
```lisp
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(custom-enabled-themes (quote (tango-dark)))
 '(custom-safe-themes
   (quote
    ("fbcdb6b7890d0ec1708fa21ab08eb0cc16a8b7611bb6517b722eba3891dfc9dd" default)))
 '(save-place t nil (saveplace))
 '(show-paren-mode t)
 '(tool-bar-mode nil))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

(require 'package)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/"))
(when (< emacs-major-version 24)
  ;; For important compatibility libraries like cl-lib
  (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/")))
(package-initialize) ;; You might already have this line

(require 'evil)
(evil-mode 1)

(require 'powerline)
(powerline-center-evil-theme)

(require 'airline-themes)
(load-theme 'airline-dark)

(setq airline-utf-glyph-branch              #xe0a0
      airline-utf-glyph-readonly            #xe0a2
      airline-utf-glyph-linenumber          #xe0a1)
```

**Comment by jacobHclarkson** [comment]
I have the same issues. The whole mode-line is just one rectangle of a single color.

**Comment by AnthonyDiGirolamo** [comment]
I just pushed some changes that may help. I think the problem was I using a function called `reduce` it's actually `cl-reduce` and I didn't include a `(require 'cl-lib)`.

The new builds should be on melpa in a few hours. Try installing version 1.7 from melpa-stable and see if that works better.

**Comment by kczapla** [comment]
It solved my issue. I will wait for the other guys response and then I will mark as solved :) 

Thanks!
