### ISSUE TITLE
vc-git-working-revision gives exact revision in Emacs 25

### ISSUE THREAD

**Issue by xuhdev** [AnthonyDiGirolamo/airline-themes#19]
Currently airline-themes relies on `vc-git-working-revision` to display the branch. However, starting from Emacs 25, `vc-git-working-revision` would give the exact revision, which is long and probably useless to display in the mode-line (see [here](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=21383) and [here](http://git.savannah.gnu.org/cgit/emacs.git/commit/lisp/vc/vc-git.el?id=21d6414a4b0f37b2381859eeebf66908b6568c31)). Can we change this to display the branch again?

**Comment by AnthonyDiGirolamo** [comment]
Just noticed this myself. Will add a fix asap.
