### ISSUE TITLE
Text Highlighting

### ISSUE THREAD

**Issue by eccentricayman** [AnthonyDiGirolamo/airline-themes#24]
Is there any way to disable the text highlighting on some of the faces?
Ex. filename in modeline

Screenshot example:
![emacs](http://i.imgur.com/w7IVn0Z.png)

The prompt for "Find File: " is highlighted, and the same goes for "M-x".

**Comment by AnthonyDiGirolamo** [comment]
You can override the settings of any face that airline modifies by using `custom-theme-set-faces`. This technique should work with other themes as well.

```elisp
  (load-theme 'airline-doom-one t)
  (custom-theme-set-faces
   'airline-doom-one
   `(minibuffer-prompt ((t (:background "#141a22" :foreground "#00B3EF" :weight bold))))
  )
```

If you want it to inherit from a different face you could use something like:

```elisp
  (load-theme 'airline-doom-one t)
  (custom-theme-set-faces
   'airline-doom-one
   `(minibuffer-prompt ((t (:foreground nil :background nil :inherit 'default))))
  )
```

**Comment by eccentricayman** [comment]
Second one works perfectly!

**Comment by YuSuu** [comment]
Thanks Anthony!
Help a lot.
