### ISSUE TITLE
Thicker mode line?

### ISSUE THREAD

**Issue by Red-Portal** [AnthonyDiGirolamo/airline-themes#29]
Hi,
How can I make the mode line thicker without breaking the theme?
Is is possible?

**Comment by AnthonyDiGirolamo** [comment]
You can set the `powerline-height` variable to something larger than your font size.

```elisp
(setq powerline-height 18)
```

Here is the variable:
https://github.com/milkypostman/powerline/blob/master/powerline.el#L108

**Comment by Red-Portal** [comment]
thanks!
