### ISSUE TITLE
Insert mode cursor is a block, not a line

### ISSUE THREAD

**Issue by EricCrosson** [AnthonyDiGirolamo/airline-themes#3]
Hey there, 

great package. I'm going to open a few issues so I remember what to examine when I've got a minute. 

When evil switches to insert mode, the default evil changes the block cursor to a line, and back when insert is exited. This behavior matches vim. I'd like to see this package emulate it successfully, because the color-changes are nice but it's silly to trade one indicator for another :)

**Comment by EricCrosson** [comment]
notes
---
I'm having luck running the following line:
```lisp
(setq evil-insert-state-cursor 'bar)
```
However, I haven't found the right spot for it in the lisp so that the line remains active throughout the natural loading process.

**Comment by AnthonyDiGirolamo** [comment]
Sorry it took me a while to get to this. I like the bar cursor in when in the gui version of emacs too. Hopefully that fixes things for you.
