### ISSUE TITLE
Some font glyphs are not rendered.

### ISSUE THREAD

**Issue by srustamo** [AnthonyDiGirolamo/airline-themes#5]
I have many `powerline` patched fonts on my system, and Vim is happy using them in both iTerm2 and gui. However, `airline-themes` seems to have rendering issues.
1. In gui, one glyph is not rendered properly. See [here](http://i.imgur.com/vZx3muk.png?1). 
2. in iTerm2 there are more problems. See [here](http://i.imgur.com/4osakWN.png?1).

What font do you use?

GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, Carbon Version 157 AppKit 1265.21) of 2015-05-01 on srmbp.local

**Comment by AnthonyDiGirolamo** [comment]
Hey @srustamo, I've been using the pragmata pro font for a long while now ( http://www.fsd.it/fonts/pragmatapro.htm ) and haven't had any issues in the terminal (rxvt) but I knew this would be an issue as the default utf separators that come with emacs powerline didn't work for me. I'm thinking of adding custom options for all the utf glyphs does that sound like it might fix things? Here is the glyphs I know of so far:

    | Symbol             | powerline    | vim-powerline |                                                
    |--------------------+--------------+---------------|                                                
    | separator.left     | '' (\ue0b0) | '⮀' (\u2b80)  |                                                
    | separator.right    | '' (\ue0b2) | '⮂' (\u2b82)  |                                                
    | subseparator.left  | '' (\ue0b1) | '⮁' (\u2b81)  |                                                
    | subseparator.right | '' (\ue0b3) | '⮃' (\u2b83)  |                                                
    | branch symbol      | '' (\ue0a0) | '⭠' (\u2b60)  |                                                
    | readonly symbol    | '' (\ue0a2) | '⭤' (\u2b64)  |                                                
    | linecolumn symbol  | '' (\ue0a1) | '⭡' (\u2b81)  |

**Comment by srustamo** [comment]
Thank you, this is excellent.
