### ISSUE TITLE
Problem with fonts

### ISSUE THREAD

**Issue by Enrico68** [AnthonyDiGirolamo/airline-themes#9]
Hello, 
I have set up airline-themes with  

````
(require 'powerline-evil)
(powerline-evil-center-color-theme)
 (require 'airline-themes)
 (load-theme 'airline-hybridline)

`````
But I have a small font [problem](http://i.imgur.com/Y1a837p.png)

**Comment by AnthonyDiGirolamo** [comment]
Hi @Enrico68, 
That missing character is the right subseparator and is a UTF character that requires a powerline patched font. You can get one from: https://github.com/powerline/fonts

There are custom variables that let you override the glyphs used if it's not working for your font. I just documented these in the README since they were missing from there. Hopefully you can use those to set a different character that works for your font.

**Comment by JonHarder** [comment]
I am certain I'm using a powerline patched font (I've tested multiple actually) and just the branch glyph appears as a box with hex in it just as it does for enrico.

**Comment by AnthonyDiGirolamo** [comment]
The box in @Enrico68's screen shot is the subseparator between the minor modes and the major mode. Is that the same for you? If you can let me know what os, terminal (or if you are using a gui emacs, which build it is), and what font you are using I can try to reproduce the error.

**Comment by Enrico68** [comment]
Anthony DiGirolamo <notifications@github.com>

@AnthonyDiGirolamo I forgot to mention I am using Emacs 24.5.1 installed with MacPorts on OSX
10.9.5. All powerline fonts are installed (Iterm and VIM powerline fonts are regularly
displayed).


> The box in @Enrico68's screen shot is the subseparator between the minor modes and the major mode. Is that the same for you? If you can let me know what os, terminal (or if you are using a gui emacs, which build it is), and what font you are using I can try to reproduce the error.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/AnthonyDiGirolamo/airline-themes/issues/9#issuecomment-144482570

--

**Comment by JonHarder** [comment]
"GNU Emacs 25.0.50.1 (x86_64-unknown-linux-gnu, GTK+ Version 2.24.23) of 2015-05-29 on jharder"

I'm running Ubuntu 14.04 with gui emacs using Droid Sans Mono for Powerline although I've had the same issue with Source Code Pro for Powerline, DejaVu Sans Mono for Powerline, and Inconsolata for Powerline.

**Comment by windrg** [comment]
I'm also experiencing this issue as same as Jon Harder.

**Comment by AnthonyDiGirolamo** [comment]
Does setting the following help?

```
(setq airline-utf-glyph-separator-left      #xe0b0
      airline-utf-glyph-separator-right     #xe0b2
      airline-utf-glyph-subseparator-left   #xe0b1
      airline-utf-glyph-subseparator-right  #xe0b3
      airline-utf-glyph-branch              #xe0a0
      airline-utf-glyph-readonly            #xe0a2
      airline-utf-glyph-linenumber          #xe0a1)
```

**Comment by windrg** [comment]
Many Thanks to you. :-)

**Comment by AnthonyDiGirolamo** [comment]
That worked? Great! I updated the readme to include setting those variables.

**Comment by srustamo** [comment]
A bit confused by 'git branch' and 'line number' symbols not showing up in gui ("Git" is shown, not the branch glyph), but they show up in iTerm2 using the same `init.el` on the same machine.

iTerm2 has an option to set "regular" font, I set it to 'Hack', and "Non-ASCII", I set it to 'PowerlineSymbols'. 

Gui font is set by `(set-face-attribute 'default nil  :family "Hack")`. Tried `(set-face-attribute 'default nil :family "Inconsolata for Powerline")` and other powerline patched fonts, no luck.
Other glyphs (right, left separators) are all fine.

OSX 10.9.5
GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, Carbon Version 157 AppKit 1265.21)

**Comment by srustamo** [comment]
Apologies to @Enrico68 if I raise a somewhat unrelated issue in his thread.

**Comment by AnthonyDiGirolamo** [comment]
Hey @srustamo I think the git branch symbol is shown via the powerline package. Looks like it will use "Git:" instead of the branch symbol in gui emacs. The line number was hidden for some reason by me. I can't remember why I did that. Will submit a fix now.

**Comment by srustamo** [comment]
The latest commit did fix the line number issue. It also fixed the branch symbol, unless some other package update affected the fix.

Let me link here the issue of GUI vs Terminal `line number` and `git` symbol rendering issue for (powerline)[https://github.com/milkypostman/powerline/issues/100], perhaps someone may find this useful.
